### ISSUE TITLE
stopgap upgrade

### ISSUE THREAD

**Issue by saylorsd** [WPRDC/wprdc-ops#19]
To prevent any serious downtime and potential loss of data, we need to migrate to the new database ASAP.  

**Steps:** 
- [x] Get a CKAN 2.10 deployment working with our new database. 
- [x] Install the necessary extensions.
- [x] Update `datajson` extension to work with 2.10
- [ ] Update(rewrite?) extension for promoted views.
- [x] Install other suggested extensions (if added in comments)
- [x] ~~Install old theme.~~ Slightly tweak default theme to fit old color scheme.

**Comment by saylorsd** [comment]
There are two important extensions that we currently can't use with CKAN 2.10: `datajson` and `featureviews`.

They're being tracked in their own issues:
#20 
#21

**Comment by saylorsd** [comment]
`datajson` is fixed. I will hold canonical/promoted/dataset-landing-page views as a last thing; it can happen after launch.   

Some final style fixes still need to be done:
- [x] pagination on datatables
- [ ] datatables buttons
- [ ] activity stream page
- [x] style private dataset badge `.dataset-private.badge`

**Comment by marikanti** [comment]
Hi @saylorsd how did you fixed the iroutes issue 

I want to redirect homepage to /dataset

**Comment by saylorsd** [comment]
@marikanti On our site (https://data.wprdc.org) we handle that by defining a redirect in a web server (nginx).

This location directive tells nginx to redirect requests to https://data.wprdc.org/ to https://data.wprdc.org/dataset/. 
```
    location ~ ^/$ {
        return 301 /dataset/;
    }
```

If you're using apache there should be a similar way of setting up a redirect.

Hope that helps.
