### ISSUE TITLE
Research how we should go about making our tools available in additional languages

### ISSUE THREAD

**Issue by saylorsd** [WPRDC/wprdc-ops#46]
Currently I know I'll need to:
- look into how to handle i18n technically
- figure out how we can get our stuff translated

**Comment by saylorsd** [comment]
possibly training materials from CTSI

**Comment by lizmo** [comment]
Dr. Maya Ragavan talk: https://ctsi.pitt.edu/about-us/events/event?eventId=289

Emailed on 2/21/24

**Comment by rgradeck** [comment]
See this paper by Pitt's Dr. Maya Ragavan https://journals.sagepub.com/doi/10.1177/15248399241236182

**Comment by lizmo** [comment]
Notes from Dr. Maya Ragavan meeting  
https://docs.google.com/document/d/1SErSxv1zzc9-XdHDt9EqwzHFIuDbsy4eK1_BL9aCZTo/edit?usp=sharing
